## NumPy Exercises  - CH V N S Jahnavi - 21BCE7842


In [21]:
#q1
!pip install numpy
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.43515827])

In [10]:
np.random.randn(25) #randn is for normal distribution

array([-1.71566434,  1.78058453, -0.81330852,  0.26616858,  0.1848012 ,
        0.34376917,  0.21300095, -2.23250537,  0.36495101, -1.24350694,
       -0.26329383,  0.09978728,  1.44841218,  0.9604335 ,  0.1359634 ,
        0.06412156, -0.05464685,  3.06811558,  0.28005907, -0.93018015,
        0.56017718,  0.85888059, -0.31025964,  0.66642643,  1.00205634])

In [11]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# NUMPY INDEXING AND SELECTION

In [12]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
mat[3][4]

20

In [15]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [16]:
mat[4]

array([21, 22, 23, 24, 25])

In [17]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
mat.sum()

325

In [19]:
mat.std()

7.211102550927978

In [20]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])